### ISSUE TITLE
Universal field names for login_user vs user

### ISSUE THREAD

**Issue by tlb1galaxy** [ansible-collections/community.cassandra#129]
##### SUMMARY

All module fields related to login (creds to access the underlying module/commands) should be the same name.
##### ISSUE TYPE
- Feature Idea
You could set YAML anchors & alias to pass credentials to any Cassandra module based on your security requirements.  And makes the distinction less confusing between modules if 'username' is used to login or set an element.

But currently you would have to set multiple 

##### COMPONENT NAME

cassandra_cqlsh
cassandra_role
cassandra_status
##### ADDITIONAL INFORMATION

```yaml

```

**Comment by rhysmeister** [comment]
Yes I was aware of this. At least some of the inconsistency is due to the fact I decided to align with the underlying tool (nodetool or cqlsh) and conventions copied from the community.mongodb modules. But I agree it would be better to align them. This should work by setting an alias... https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec

# files using the common args spec

> grep cassandra_common_argument_spec -l plugins/modules/*.py
> plugins/modules/cassandra_autocompaction.py
> plugins/modules/cassandra_backup.py
> plugins/modules/cassandra_binary.py
> plugins/modules/cassandra_cleanup.py
> plugins/modules/cassandra_compactionthreshold.py
> plugins/modules/cassandra_compactionthroughput.py
> plugins/modules/cassandra_drain.py
> plugins/modules/cassandra_flush.py
> plugins/modules/cassandra_gossip.py
> plugins/modules/cassandra_handoff.py
> plugins/modules/cassandra_interdcstreamthroughput.py
> plugins/modules/cassandra_schema.py
> plugins/modules/cassandra_status.py
> plugins/modules/cassandra_stopdaemon.py
> plugins/modules/cassandra_streamthroughput.py
> plugins/modules/cassandra_thrift.py
> plugins/modules/cassandra_traceprobability.py
> plugins/modules/cassandra_upgradesstables.py
> plugins/modules/cassandra_verify.py

# modules not using the common arg spec

> grep cassandra_common_argument_spec -L plugins/modules/*.py
> plugins/modules/cassandra_cqlsh.py
> plugins/modules/cassandra_keyspace.py
> plugins/modules/cassandra_role.py
> plugins/modules/cassandra_table.py

# Proposal to align…

- Add aliases login_user, login_password, login_host and login_port to cassandra_common_argument_spec
- Add aliases login_user, login_password, login_host and login_port to cassandra_cqlsh.py
- cassandra_keyspace.py - OK (Maybe refactor this??)
- cassandra_role.py - OK
- cassandra_table.py - OK

Then all modules would have the login_* parameters as an option.

**Comment by tlb1galaxy** [comment]
Hello Rhys,
I figured it was due to the fact it was aligned with the underlying tools.  Hopefully the Cassandra developers in the near future can align their tools too.
Thanks

**Comment by rhysmeister** [comment]
I've just merged a change that implements the login_* across all modules. Added a few tests and seems to work.

Cheers,

Rhys
